package com.example.utils

object AppStrings {
    var currentLanguage: String = "ar" // Default Arabic

    private val arStrings = mapOf(
        "app_name" to "ChatConnect",
        "chats" to "المحادثات",
        "status" to "الحالات",
        "calls" to "المكالمات",
        "contacts" to "جهات الاتصال",
        "settings" to "الإعدادات",
        "search" to "بحث...",
        "search_by_id" to "ابحث بالـ ID (10 أرقام)",
        "type_message" to "مراسلة",
        "online" to "متصل الآن",
        "last_seen" to "آخر ظهور",
        "typing" to "يكتب الآن...",
        "send" to "إرسال",
        "voice_message" to "رسالة صوتية",
        "recording" to "جاري التسجيل...",
        "slide_to_cancel" to "اسحب للإلغاء",
        "add_contact" to "إضافة جهة اتصال",
        "enter_custom_id" to "أدخل معرف المستخدم (ID):",
        "enter_nickname" to "الاسم المستعار في جهات الاتصال:",
        "add" to "إضافة",
        "cancel" to "إلغاء",
        "user_not_found" to "لم يتم العثور على مستخدم بهذا المعرف.",
        "already_contact" to "هذا المستخدم موجود بالفعل في جهات الاتصال.",
        "my_id" to "المعرف الخاص بي (ID)",
        "copy_id" to "نسخ المعرف",
        "id_copied" to "تم نسخ المعرف!",
        "profile" to "الملف الشخصي",
        "edit_profile" to "تعديل الملف الشخصي",
        "username" to "اسم المستخدم",
        "bio" to "النبذة الشخصية",
        "save" to "حفظ التغيرات",
        "change_photo" to "تغيير الصورة",
        "delete_photo" to "حذف الصورة",
        "my_status" to "حالاتي",
        "add_status" to "إضافة حالة جديدة",
        "recent_updates" to "التحديثات الحديثة",
        "viewed_updates" to "التحديثات المشاهدة",
        "create_status" to "إنشاء حالة",
        "text_status" to "حالة نصية",
        "image_status" to "حالة صورة",
        "video_status" to "حالة فيديو",
        "caption" to "إضافة وصف...",
        "post_status" to "نشر الحالة",
        "views" to "المشاهدات",
        "views_count" to "مشاهدة",
        "status_privacy" to "خصوصية الحالة",
        "who_can_see_status" to "من يمكنه رؤية حالاتي",
        "my_contacts" to "جهات اتصالي",
        "my_contacts_except" to "جهات اتصالي باستثناء...",
        "only_share_with" to "المشاركة فقط مع...",
        "muted_updates" to "التحديثات المكتومة",
        "mute_status_title" to "كتم تحديثات الحالة؟",
        "mute_status_desc" to "لن تظهر التحديثات الجديدة من هذا المستخدم في أعلى قائمة الحالات.",
        "unmute_status_title" to "إلغاء كتم تحديثات الحالة؟",
        "unmute_status_desc" to "ستظهر التحديثات الجديدة من هذا المستخدم في التحديثات الحديثة.",
        "delete_status_title" to "حذف هذه الحالة؟",
        "delete_status_desc" to "سيتم حذف هذه الحالة لجميع جهات الاتصال الخاصة بك فوراً.",
        "delete" to "حذف",
        "reply_to_status" to "رد على الحالة...",
        "reply_sent" to "تم إرسال الرد في المحادثة!",
        "no_viewers_yet" to "لم يشاهد أحد حالتك بعد",
        "viewed_by" to "قائمة المشاهدات",
        "camera" to "الكاميرا",
        "gallery" to "المعرض",
        "text" to "نص",
        "status_posted" to "تم نشر الحالة بنجاح!",
        "status_deleted" to "تم حذف الحالة بنجاح!",
        "status_expired" to "هذه الحالة منتهية الصلاحية",
        "viewers_list" to "مشاهدات الحالة",
        "no_views_yet" to "لم يشاهد أحد حالتك بعد",
        "delete_status" to "حذف الحالة",
        "confirm_delete_status" to "هل أنت متأكد من حذف هذه الحالة؟ سيتم إزالتها نهائياً.",
        "discard_status" to "تجاهل الحالة؟",
        "confirm_discard_status" to "هل تريد إلغاء التعديلات وتجاهل هذه الحالة؟",
        "write_status_hint" to "اكتب حالتك هنا...",
        "updates_count" to "تحديثات",
        "discard_status_title" to "تجاهل الحالة؟",
        "discard_status_desc" to "هل أنت متأكد من رغبتك في إلغاء نشر هذه الحالة؟",
        "discard" to "تجاهل",
        "save_privacy" to "حفظ الخصوصية",
        "contacts_selected" to "تم تحديد",
        "audio_call" to "مكالمة صوتية",
        "video_call" to "مكالمة فيديو",
        "incoming_call" to "مكالمة واردة...",
        "calling" to "جاري الاتصال...",
        "ringing" to "يرن...",
        "connecting" to "جاري الربط...",
        "reconnecting" to "إعادة الاتصال...",
        "call_connected" to "متصل",
        "call_ended" to "انتهت المكالمة",
        "call_declined" to "تم رفض المكالمة",
        "call_missed" to "مكالمة فائتة",
        "call_busy" to "الخط مشغول",
        "call_failed" to "فشل الاتصال",
        "accept" to "قبول",
        "reject" to "رفض",
        "end_call" to "إنهاء المكالمة",
        "mute" to "كتم",
        "unmute" to "إلغاء الكتم",
        "speaker" to "المكبر",
        "earpiece" to "سماعة الهاتف",
        "bluetooth" to "بلوتوث",
        "audio_output" to "مخرج الصوت",
        "add_participant" to "إضافة مشارك",
        "minimize" to "تصغير",
        "return_to_chat" to "العودة للمحادثة",
        "flip_camera" to "تبديل الكاميرا",
        "camera_off" to "إيقاف الكاميرا",
        "camera_on" to "تشغيل الكاميرا",
        "dtls_srtp_badge" to "مشفرة بتقنية DTLS-SRTP (E2EE)",
        "network_poor" to "جودة الشبكة غير مستقرة، جاري المحاولة...",
        "permission_mic_camera_required" to "يلزم إذن الميكروفون والكاميرا لتشغيل المكالمات المشفرة.",
        "create_group" to "إنشاء مجموعة جديدة",
        "group_name" to "اسم المجموعة",
        "select_members" to "اختيار الأعضاء",
        "create" to "إنشاء",
        "owner" to "المالك",
        "admin" to "مشرف",
        "member" to "عضو",
        "make_admin" to "تعيين كمشرف",
        "remove_admin" to "إلغاء المشرف",
        "remove_member" to "إزالة من المجموعة",
        "leave_group" to "مغادرة المجموعة",
        "privacy" to "الخصوصية",
        "blocked_users" to "المستخدمون المحظورون",
        "block" to "حظر",
        "unblock" to "رفع الحظر",
        "blocked_message" to "لا يمكنك إرسال رسائل لهذا المستخدم لأنك حظرته.",
        "linked_devices" to "الأجهزة المرتبطة",
        "delete_account" to "حذف الحساب",
        "delete_account_confirm" to "هل أنت تأكد من رغبتك في حذف الحساب نهائياً؟",
        "switch_account" to "تبديل الحساب / تسجيل الخروج",
        "register" to "إنشاء حساب جديد",
        "login" to "تسجيل الدخول",
        "enter_username" to "أدخل اسمك",
        "enter_password" to "أدخل كلمة المرور",
        "change_password" to "تغيير كلمة المرور",
        "current_password" to "كلمة المرور الحالية (القديمة)",
        "new_password" to "كلمة المرور الجديدة",
        "confirm_password" to "تأكيد كلمة المرور الجديدة",
        "password_changed_success" to "تم التحقق وتحديث كلمة المرور بنجاح!",
        "passwords_do_not_match" to "كلمتا المرور غير متطابقتين",
        "incorrect_password" to "كلمة المرور القديمة غير صحيحة!",
        "password_min_length" to "يجب ألا تقل كلمة المرور عن 6 أحرف",
        "enter_password_to_switch" to "أدخل كلمة المرور لفتح هذا الحساب:",
        "password_protected" to "الحساب محمي بكلمة مرور",
        "security_and_password" to "الأمان وكلمة المرور",
        "verify_old_password_notice" to "يتم التحقق بدقة من كلمة المرور القديمة أولاً قبل تطبيق التحديث لحماية حسابك.",
        "verifying_and_updating" to "جارٍ التحقق وتحديث كلمة المرور...",
        "old_password_verified" to "تم التحقق من كلمة المرور القديمة",
        "old_password_incorrect" to "كلمة المرور القديمة غير صحيحة! تعذر التحديث.",
        "linked_devices" to "الأجهزة المرتبطة والجلسات النشطة",
        "linked_devices_desc" to "إدارة الأجهزة المتصلة بحسابك وجلسات تسجيل الدخول النشطة مع صلاحية إنهاء الوصول",
        "this_device" to "هذا الجهاز (الجهاز الحالي)",
        "active_now" to "نشط الآن",
        "other_devices" to "الأجهزة المرتبطة الأخرى",
        "no_other_devices" to "لا توجد أجهزة أخرى مرتبطة بحسابك حالياً",
        "revoke_session" to "إنهاء الجلسة",
        "revoke_all_other" to "تسجيل الخروج من جميع الأجهزة الأخرى",
        "revoke_confirm_title" to "إنهاء جلسة الجهاز؟",
        "revoke_confirm_msg" to "هل أنت متأكد من رغبتك في تسجيل الخروج من هذا الجهاز؟ سيتم إلغاء صلاحية الوصول فوراً.",
        "revoke_all_confirm_title" to "تسجيل الخروج من جميع الأجهزة الأخرى؟",
        "revoke_all_confirm_msg" to "سيتم تسجيل الخروج وإلغاء صلاحية جميع الجلسات النشطة على الأجهزة الأخرى فوراً.",
        "link_device" to "ربط جهاز جديد",
        "link_device_desc" to "استخدم رمز الاستجابة السريعة (QR) أو كود الربط لمزامنة الحساب على الويب أو سطح المكتب.",
        "link_device_instruction" to "1. افتح web.chatconnect.app على جهاز الكمبيوتر\n2. وجّه الكاميرا نحو الشاشة أو اضغط محاكاة الربط لتوصيل جلسة جديدة فوراً",
        "simulate_link_web" to "محاكاة ربط جهاز كمبيوتر (Web Client)",
        "simulate_link_desktop" to "محاكاة ربط تطبيق سطح المكتب (Desktop)",
        "session_revoked_success" to "تم إنهاء الجلسة وإلغاء اتصال الجهاز بنجاح!",
        "all_sessions_revoked_success" to "تم تسجيل الخروج من جميع الأجهزة الأخرى بنجاح!",
        "device_linked_success" to "تم ربط الجهاز الجديد بنجاح!",
        "language" to "اللغة",
        "arabic" to "العربية",
        "english" to "English",
        "dark_mode" to "الوضع الداكن",
        "encrypted_disclaimer" to "المحادثات والمكالمات محمية بآلية تشفير تام من طرف إلى طرف.",
        "about_app" to "حول التطبيق",
        "app_version" to "الإصدار 1.0",
        "app_version_label" to "إصدار التطبيق",
        "chat" to "محادثة",
        "call" to "مكالمة",
        "e2ee_encrypted" to "مشفرة تماماً بين الطرفين",
        "e2ee_call_desc" to "مكالمة آمنة مشفرة بتقنية E2EE (DTLS-SRTP & AES-256)",
        "developer_team" to "فريق التطوير: ChatConnect Team",
        "all_rights_reserved" to "جميع الحقوق محفوظة © 2026"
    )

    private val enStrings = mapOf(
        "app_name" to "ChatConnect",
        "chats" to "Chats",
        "status" to "Status",
        "calls" to "Calls",
        "contacts" to "Contacts",
        "settings" to "Settings",
        "search" to "Search...",
        "search_by_id" to "Search by 10-digit User ID",
        "type_message" to "Message",
        "online" to "Online",
        "last_seen" to "Last seen",
        "typing" to "typing...",
        "send" to "Send",
        "voice_message" to "Voice message",
        "recording" to "Recording...",
        "slide_to_cancel" to "Slide to cancel",
        "add_contact" to "Add Contact",
        "enter_custom_id" to "Enter User ID (10 digits):",
        "enter_nickname" to "Contact Nickname:",
        "add" to "Add",
        "cancel" to "Cancel",
        "user_not_found" to "User not found with this ID.",
        "already_contact" to "This user is already in your contacts.",
        "my_id" to "My Unique User ID",
        "copy_id" to "Copy ID",
        "id_copied" to "ID copied to clipboard!",
        "profile" to "Profile",
        "edit_profile" to "Edit Profile",
        "username" to "Username",
        "bio" to "About",
        "save" to "Save Changes",
        "change_photo" to "Change Photo",
        "delete_photo" to "Delete Photo",
        "my_status" to "My Status",
        "add_status" to "Add status update",
        "recent_updates" to "Recent updates",
        "viewed_updates" to "Viewed updates",
        "create_status" to "Create Status",
        "text_status" to "Text Status",
        "image_status" to "Image Status",
        "video_status" to "Video Status",
        "caption" to "Add caption...",
        "post_status" to "Post Status",
        "views" to "Views",
        "views_count" to "views",
        "status_privacy" to "Status Privacy",
        "who_can_see_status" to "Who can see my status updates",
        "my_contacts" to "My contacts",
        "my_contacts_except" to "My contacts except...",
        "only_share_with" to "Only share with...",
        "muted_updates" to "Muted Updates",
        "mute_status_title" to "Mute status updates?",
        "mute_status_desc" to "New status updates from this contact will not appear at the top of your status list.",
        "unmute_status_title" to "Unmute status updates?",
        "unmute_status_desc" to "New status updates from this contact will appear under recent updates.",
        "delete_status_title" to "Delete this status?",
        "delete_status_desc" to "This status will be deleted for all of your contacts immediately.",
        "delete" to "Delete",
        "reply_to_status" to "Reply to status...",
        "reply_sent" to "Reply sent to chat!",
        "no_viewers_yet" to "No views yet",
        "viewed_by" to "Viewed by",
        "camera" to "Camera",
        "gallery" to "Gallery",
        "text" to "Text",
        "status_posted" to "Status posted successfully!",
        "status_deleted" to "Status deleted successfully!",
        "status_expired" to "This status has expired",
        "viewers_list" to "Status Views",
        "no_views_yet" to "No views yet",
        "delete_status" to "Delete Status",
        "confirm_delete_status" to "Are you sure you want to delete this status? It will be removed permanently.",
        "discard_status" to "Discard status?",
        "confirm_discard_status" to "Are you sure you want to discard your changes to this status?",
        "write_status_hint" to "Type a status...",
        "updates_count" to "updates",
        "discard_status_title" to "Discard status?",
        "discard_status_desc" to "Are you sure you want to discard this status update?",
        "discard" to "Discard",
        "save_privacy" to "Save Privacy",
        "contacts_selected" to "selected",
        "audio_call" to "Audio Call",
        "video_call" to "Video Call",
        "incoming_call" to "Incoming call...",
        "calling" to "Calling...",
        "ringing" to "Ringing...",
        "connecting" to "Connecting...",
        "reconnecting" to "Reconnecting...",
        "call_connected" to "Connected",
        "call_ended" to "Call ended",
        "call_declined" to "Call declined",
        "call_missed" to "Missed call",
        "call_busy" to "Line busy",
        "call_failed" to "Call failed",
        "accept" to "Accept",
        "reject" to "Reject",
        "end_call" to "End Call",
        "mute" to "Mute",
        "unmute" to "Unmute",
        "speaker" to "Speaker",
        "earpiece" to "Earpiece",
        "bluetooth" to "Bluetooth",
        "audio_output" to "Audio Output",
        "add_participant" to "Add Participant",
        "minimize" to "Minimize",
        "return_to_chat" to "Return to Chat",
        "flip_camera" to "Flip Camera",
        "camera_off" to "Turn Off Camera",
        "camera_on" to "Turn On Camera",
        "dtls_srtp_badge" to "Encrypted DTLS-SRTP (E2EE)",
        "network_poor" to "Network unstable, reconnecting...",
        "permission_mic_camera_required" to "Microphone and camera permissions are required to start encrypted calls.",
        "create_group" to "New Group",
        "group_name" to "Group Name",
        "select_members" to "Select Members",
        "create" to "Create",
        "owner" to "Owner",
        "admin" to "Admin",
        "member" to "Member",
        "make_admin" to "Make Admin",
        "remove_admin" to "Dismiss as Admin",
        "remove_member" to "Remove from Group",
        "leave_group" to "Leave Group",
        "privacy" to "Privacy",
        "blocked_users" to "Blocked Users",
        "block" to "Block",
        "unblock" to "Unblock",
        "blocked_message" to "You cannot send messages to this blocked user.",
        "linked_devices" to "Linked Devices",
        "delete_account" to "Delete Account",
        "delete_account_confirm" to "Are you sure you want to permanently delete your account?",
        "switch_account" to "Switch Account / Logout",
        "register" to "Create Account",
        "login" to "Log In",
        "enter_username" to "Enter Your Name",
        "enter_password" to "Enter Password",
        "change_password" to "Change Password",
        "current_password" to "Current (Old) Password",
        "new_password" to "New Password",
        "confirm_password" to "Confirm New Password",
        "password_changed_success" to "Password successfully verified and updated in Firebase Auth!",
        "passwords_do_not_match" to "Passwords do not match",
        "incorrect_password" to "Old password is incorrect!",
        "password_min_length" to "Password must be at least 6 characters for Firebase Auth",
        "enter_password_to_switch" to "Enter password to access this account:",
        "password_protected" to "Account is password protected",
        "security_and_password" to "Security & Firebase Auth Account",
        "verify_old_password_notice" to "Your old password is verified before applying the update to your Firebase Auth account.",
        "verifying_and_updating" to "Verifying and updating Firebase Auth account...",
        "old_password_verified" to "Old password verified",
        "old_password_incorrect" to "Old password is incorrect! Failed to update account.",
        "linked_devices" to "Linked Devices & Active Sessions",
        "linked_devices_desc" to "Manage connected devices and active authentication sessions with secure revocation",
        "this_device" to "This Device (Current Session)",
        "active_now" to "Active Now",
        "other_devices" to "Other Linked Devices",
        "no_other_devices" to "No other devices linked to your account",
        "revoke_session" to "Revoke Session",
        "revoke_all_other" to "Log Out from All Other Devices",
        "revoke_confirm_title" to "Revoke Device Session?",
        "revoke_confirm_msg" to "Are you sure you want to log out this device? Its access will be immediately terminated.",
        "revoke_all_confirm_title" to "Log Out from All Other Devices?",
        "revoke_all_confirm_msg" to "All active sessions on linked web browsers, desktops, and tablets will be immediately revoked.",
        "link_device" to "Link a New Device",
        "link_device_desc" to "Scan the QR code or simulate connecting a new web or desktop terminal.",
        "link_device_instruction" to "1. Open web.chatconnect.app on your computer\n2. Point camera to QR or tap to simulate instant link",
        "simulate_link_web" to "Simulate Link Web Client (Chrome)",
        "simulate_link_desktop" to "Simulate Link Desktop App (macOS)",
        "session_revoked_success" to "Device session successfully revoked!",
        "all_sessions_revoked_success" to "All other devices logged out successfully!",
        "device_linked_success" to "New device linked successfully!",
        "language" to "Language",
        "arabic" to "العربية",
        "english" to "English",
        "dark_mode" to "Dark Mode",
        "encrypted_disclaimer" to "Chats and calls are secured with strict per-user data isolation and encryption protocols.",
        "about_app" to "About App",
        "app_version" to "Version 1.0",
        "app_version_label" to "App Version",
        "chat" to "Chat",
        "call" to "Call",
        "e2ee_encrypted" to "End-to-End Encrypted",
        "e2ee_call_desc" to "Secure call protected by E2EE (DTLS-SRTP & AES-256)",
        "developer_team" to "Development: ChatConnect Team",
        "all_rights_reserved" to "All rights reserved © 2026"
    )

    fun get(key: String): String {
        val map = if (currentLanguage == "en") enStrings else arStrings
        return map[key] ?: key
    }
}
